language: go
go:
- "1.11.x"
install:
- go get -u -v golang.org/x/tools/cmd/goimports
- go get -u -v golang.org/x/lint/golint
- go get -u -v github.com/mattn/goveralls
env:
  GO111MODULE: "on"
script:
- make CI_TEST=true
- $GOPATH/bin/goveralls -coverprofile=cover.out -service=travis-ci
